// OTP Sending
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';

// OTP Verification
export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';


export const USER_OTP_RESEND_REQUEST = 'USER_OTP_RESEND_REQUEST';
export const USER_OTP_RESEND_SUCCESS = 'USER_OTP_RESEND_SUCCESS';
export const USER_OTP_RESEND_FAIL = 'USER_OTP_RESEND_FAIL';
